// Generated by CoffeeScript 1.9.0
(function() {
  var assert, metatrader;

  assert = require('chai').assert;

  metatrader = require('../../lib/metatrader');

  describe('Metatrader', function() {
    it('exists interface InterfaceClient', function() {
      return assert.typeOf(metatrader.InterfaceClient, 'function');
    });
    it('exists interface InterfaceCreator', function() {
      return assert.typeOf(metatrader.InterfaceCreator, 'function');
    });
    it('exists interface InterfaceExecutor', function() {
      return assert.typeOf(metatrader.InterfaceExecutor, 'function');
    });
    it('exists interface InterfaceCommand', function() {
      return assert.typeOf(metatrader.InterfaceCommand, 'function');
    });
    it('exists class NetClient', function() {
      return assert.typeOf(metatrader.NetClient, 'function');
    });
    it('exists class NetCreator', function() {
      return assert.typeOf(metatrader.NetCreator, 'function');
    });
    it('exists class NetExecutor', function() {
      return assert.typeOf(metatrader.NetExecutor, 'function');
    });
    it('exists class QuotesCommand', function() {
      return assert.typeOf(metatrader.QuotesCommand, 'function');
    });
    return it('exists class CandlesCommand', function() {
      return assert.typeOf(metatrader.CandlesCommand, 'function');
    });
  });

}).call(this);
