// Generated by CoffeeScript 1.9.0
(function() {
  var app, config, creator, express, metatrader, server, _loop;

  metatrader = require('./index.js');

  config = require('./config.js');

  creator = new metatrader.HttpsCreator();

  _loop = function() {
    var client, command, executor;
    console.log('loop start');
    executor = creator.createExecutor(config);
    client = creator.createClient(executor);
    console.log(client);
    command = new metatrader.TradingSymbolCommand();
    client.send(command, (function(_this) {
      return function(data) {
        var trader_symbol;
        trader_symbol = data;
        return console.log('Result', data);
      };
    })(this), function(error) {
      return console.log('Handler %s', error);
    });
    return console.log('loop end');
  };

  express = require('express');

  app = express();

  app.get('/trader_symbol', function(req, res) {
    return res.send(JSON.stringify(trader_symbol));
  });

  server = app.listen(4000, function() {
    var host, port;
    host = server.address().address;
    port = server.address().port;
    return console.log('MetaTrader Proxy app listening at http://%s:%s', host, port);
  });

  _loop();

}).call(this);
