// Generated by CoffeeScript 1.9.0
(function() {
  var klass, should;

  should = require('chai').should();

  klass = new (require('../../../lib/metatrader').InterfaceCreator);

  describe('InterfaceCreator', function() {
    it('implmenets createClient method', function() {
      return klass.createClient.should.be.a('function');
    });
    return it('implmenets createExecutor method', function() {
      return klass.createExecutor.should.be.a('function');
    });
  });

}).call(this);
