// Generated by CoffeeScript 1.9.0
(function() {
  var klass, should;

  should = require('chai').should();

  klass = new (require('../../../lib/metatrader').InterfaceCommand);

  describe('InterfaceCommand', function() {
    it('implements generateRequest method', function() {
      return klass.generateRequest.should.be.a('function');
    });
    it('implements stopReadCallback method', function() {
      return klass.stopReadCallback.should.be.a('function');
    });
    return it('implements processResponse method', function() {
      return klass.processResponse.should.be.a('function');
    });
  });

}).call(this);
