// Generated by CoffeeScript 1.9.0
(function() {
  var assert, klass, should, sinon;

  assert = require('chai').assert;

  sinon = require('sinon');

  should = require('chai').should();

  klass = require('../../../lib/metatrader').TradingSymbolCommand;

  describe('TradingSymbolCommand', function() {
    var object;
    object = void 0;
    before(function() {
      return object = new klass();
    });
    describe('#constructor', function() {
      return it('exists method', function() {
        return object.constructor.should.be.a('function');
      });
    });
    describe('#generateRequest', function() {
      return it('exists method', function() {
        return object.generateRequest.should.be.a('function');
      });
    });
    return describe('#processResponse', function() {
      var response, result;
      response = "";
      result = {};
      it('exists method', function() {
        return object.processResponse.should.be.a('function');
      });
      return it('returns is valid', function() {
        return assert.deepEqual(object.processResponse(response), result);
      });
    });
  });

}).call(this);
